package com.tournaments.presentation.request;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents AI-interpreted search intent from natural language query.
 * Generated by AiGatewayService and used to filter tournaments.
 */
public class SearchIntent {
    @JsonProperty("gameName")
    private String gameName;

    @JsonProperty("dateFrom")
    private LocalDateTime dateFrom;

    @JsonProperty("dateTo")
    private LocalDateTime dateTo;

    @JsonProperty("priceMin")
    private BigDecimal priceMin;

    @JsonProperty("priceMax")
    private BigDecimal priceMax;

    @JsonProperty("isOnline")
    private Boolean isOnline;

    @JsonProperty("keywords")
    private List<String> keywords;

    @JsonProperty("confidence")
    private Double confidence;

    public SearchIntent() {}

    public SearchIntent(String gameName, LocalDateTime dateFrom, LocalDateTime dateTo,
                        BigDecimal priceMin, BigDecimal priceMax, Boolean isOnline,
                        List<String> keywords, Double confidence) {
        this.gameName = gameName;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.priceMin = priceMin;
        this.priceMax = priceMax;
        this.isOnline = isOnline;
        this.keywords = keywords;
        this.confidence = confidence;
    }

    // Getters and Setters
    public String getGameName() { return gameName; }
    public void setGameName(String gameName) { this.gameName = gameName; }

    public LocalDateTime getDateFrom() { return dateFrom; }
    public void setDateFrom(LocalDateTime dateFrom) { this.dateFrom = dateFrom; }

    public LocalDateTime getDateTo() { return dateTo; }
    public void setDateTo(LocalDateTime dateTo) { this.dateTo = dateTo; }

    public BigDecimal getPriceMin() { return priceMin; }
    public void setPriceMin(BigDecimal priceMin) { this.priceMin = priceMin; }

    public BigDecimal getPriceMax() { return priceMax; }
    public void setPriceMax(BigDecimal priceMax) { this.priceMax = priceMax; }

    public Boolean getIsOnline() { return isOnline; }
    public void setIsOnline(Boolean isOnline) { this.isOnline = isOnline; }

    public List<String> getKeywords() { return keywords; }
    public void setKeywords(List<String> keywords) { this.keywords = keywords; }

    public Double getConfidence() { return confidence; }
    public void setConfidence(Double confidence) { this.confidence = confidence; }

    @Override
    public String toString() {
        return "SearchIntent{" +
                "gameName='" + gameName + '\'' +
                ", dateFrom=" + dateFrom +
                ", dateTo=" + dateTo +
                ", priceMin=" + priceMin +
                ", priceMax=" + priceMax +
                ", isOnline=" + isOnline +
                ", keywords=" + keywords +
                ", confidence=" + confidence +
                '}';
    }
}
